apiVersion: 1

# List of data sources to insert/update
datasources:
  # TimescaleDB data source
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: sensor_data
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1500  # PostgreSQL 15
      timescaledb: true
    editable: true
