{
 "title": "Nginx Dashboard",
 "tags": [
  "system",
  "infrastructure",
  "web"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Nginx Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nginx Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "HTTP Requests"
    }
   ]
  },
  {
   "title": "Nginx Connections Handled Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_handled[5m])",
     "legendFormat": "Connections Handled"
    }
   ]
  },
  {
   "title": "Nginx Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Active" },
    { "expr": "nginx_connections_waiting", "legendFormat": "Waiting" }
   ]
  },
  {
   "title": "Nginx Connection I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_connections_reading", "legendFormat": "Reading" },
    { "expr": "nginx_connections_writing", "legendFormat": "Writing" }
   ]
  }
 ]
}